feat(es7): make mds compatible with es7
uc-cdis/metadata-service pull request #96
Opened 2023-08-25 19:02 UTC by thanh-nguyen-dang

Jira Ticket: [PXP-11011](https://ctds-planx.atlassian.net/browse/PXP-11011)
### New Features

### Breaking Changes

### Bug Fixes

### Improvements

### Dependency updates

### Deployment changes

2023-09-28 16:14 UTC, craigrbarnes submitted a review, later dismissed
The changes are fine with me. I looked and ran the code during it's development.

2023-11-08 18:57 UTC, mfshao requested changes

2023-11-08 18:57 UTC, mfshao commented on src/mds/agg_mds/adapters.py
> +        print(results)
why adding all these `print()` in this file? Are they for debugging? If so, please changes them to use `logger.debug()`

2023-11-08 20:37 UTC, mfshao approved these changes

2023-11-09 03:35 UTC, merged